name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

strategy:
  matrix:
    ruby-version: [2.7.x, 3.0.x]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install apt deps
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg gnuplot-nox
      - name: Install gem deps
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
